name: buhaychat
description: Chat application imitating iMessage.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  firebase_core: 0.2.5+1 #add dependency for Firebase Core
  cupertino_icons: ^0.1.2
  cloud_firestore: 0.8.2+3
  firebase_auth: 0.7.0
  firebase_messaging: 2.1.0
  google_sign_in: 3.2.4
  intl: 0.15.7
#  video_player: 0.9.0
#  firebase_storage: 1.0.4
#  camera: 0.2.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/btn_google_signin.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700